-- 采购建议单表
DROP TABLE IF EXISTS purchase_suggestion;
CREATE TABLE purchase_suggestion (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    suggestion_no VARCHAR(64) NOT NULL COMMENT '采购建议单号',
    shop_id VARCHAR(64) DEFAULT NULL COMMENT '门店ID',
    shop_name VARCHAR(100) DEFAULT NULL COMMENT '门店名称',
    forecast_start_date DATE DEFAULT NULL COMMENT '预测开始日期',
    forecast_end_date DATE DEFAULT NULL COMMENT '预测结束日期',
    forecast_days INT DEFAULT 7 COMMENT '预测天数',
    status TINYINT DEFAULT 10 COMMENT '状态：10待确认 20已确认 30已推送ERP 40已生成采购单 50已驳回',
    erp_purchase_suggestion_id VARCHAR(64) DEFAULT NULL COMMENT 'ERP采购建议单ID',
    erp_purchase_order_id VARCHAR(64) DEFAULT NULL COMMENT 'ERP采购订单ID',
    total_suggested_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '建议采购总数量',
    total_suggested_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '建议采购总金额',
    total_confirmed_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '确认采购总数量',
    total_confirmed_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '确认采购总金额',
    confirm_remark VARCHAR(500) DEFAULT NULL COMMENT '确认备注',
    confirm_date DATE DEFAULT NULL COMMENT '确认日期',
    confirm_user_id BIGINT DEFAULT NULL COMMENT '确认人ID',
    confirm_user_name VARCHAR(50) DEFAULT NULL COMMENT '确认人姓名',
    push_erp_status TINYINT DEFAULT 0 COMMENT '推送ERP状态：0未推送 1推送中 2推送成功 3推送失败',
    push_erp_error VARCHAR(500) DEFAULT NULL COMMENT '推送ERP错误信息',
    generate_type TINYINT DEFAULT 1 COMMENT '生成类型：1自动生成（离线恢复） 2手动生成',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_suggestion_no (suggestion_no),
    KEY idx_shop_id (shop_id),
    KEY idx_status (status),
    KEY idx_create_time (create_time),
    KEY idx_push_erp_status (push_erp_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购建议单表';

-- 采购建议单明细表
DROP TABLE IF EXISTS purchase_suggestion_item;
CREATE TABLE purchase_suggestion_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    suggestion_id BIGINT NOT NULL COMMENT '采购建议单ID',
    suggestion_no VARCHAR(64) NOT NULL COMMENT '采购建议单号',
    product_id BIGINT NOT NULL COMMENT '商品ID',
    erp_goods_id VARCHAR(64) DEFAULT NULL COMMENT 'ERP商品ID',
    product_name VARCHAR(200) NOT NULL COMMENT '商品名称',
    category_name VARCHAR(100) DEFAULT NULL COMMENT '分类名称',
    unit VARCHAR(20) DEFAULT NULL COMMENT '单位',
    historical_sales_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '历史销售数量（预测周期内）',
    daily_average_sales DECIMAL(12,4) DEFAULT 0.0000 COMMENT '日均销量',
    forecast_sales_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '预测销售数量',
    current_stock INT DEFAULT 0 COMMENT '当前库存',
    available_stock INT DEFAULT 0 COMMENT '可用库存',
    safety_stock INT DEFAULT 0 COMMENT '安全库存',
    suggested_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '建议采购数量',
    purchase_price DECIMAL(10,2) DEFAULT 0.00 COMMENT '采购单价',
    suggested_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '建议采购金额',
    confirmed_quantity DECIMAL(12,2) DEFAULT 0.00 COMMENT '确认采购数量',
    confirmed_amount DECIMAL(12,2) DEFAULT 0.00 COMMENT '确认采购金额',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    is_deleted TINYINT DEFAULT 0 COMMENT '逻辑删除：0未删除 1已删除',
    PRIMARY KEY (id),
    KEY idx_suggestion_id (suggestion_id),
    KEY idx_product_id (product_id),
    KEY idx_erp_goods_id (erp_goods_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采购建议单明细表';
